# _config.yml

# Site configuration
title: "Devs' Shitposts."
description: "my Shitpost status."
url: "https://wwquen3568.github.io"
baseurl: ""  # Leave empty for user/organization GitHub Pages

# Theme-related settings
paginate: 5  # Number of posts per page
theme: null  # We're using a custom theme, so leave this as null

# Optional social links
email: "wwquen3568@marketian.com"
github: "wwquen3568"
# twitter: "your_twitter_username"


# Exclude folders from the build
exclude:
  - assets/
